services:
  - docker:20.10.3-dind

stages:
  - compile and test
  - build jar
  - build and push docker image

compile-test-job:
  image: gradle:6.8.3-jdk15
  stage: compile and test
  script:
    - gradle clean test

build-jar-job:
  image: gradle:6.8.3-jdk15
  stage: build jar
  script:
    - gradle bootJar


docker-build-job:
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
  image: docker:stable
  stage: build and push docker image
  script:
    - docker build -t $DOCKER_REPO .
    - echo "$DOCKER_PASSWORD" | docker login --username djagielo --password-stdin docker.io
    - docker push $DOCKER_REPO

cache:
  paths:
    - .m2/repository