server:
  port: 9999
spring:
  datasource:
    url: ${MARIA_DB_URL}
    username: ${MARIA_DB_USER}
    password: ${MARIA_DB_PASS}
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}

taskService:
  url: http://localhost:9999