version: "3.9"
services:
  mariadb:
    image: "mariadb:10.6"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=ambicion
      - MARIADB_USER=ambicion-service
      - MARIADB_PASSWORD=password
  ambicion-service:
    image: bettercode.dev/ambicion-service:${CIRCLE_BRANCH}
    environment:
      - SPRING_PROFILES_ACTIVE=ct
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
    ports:
      - "9999:9999"
    depends_on:
      - mariadb