version: "3.9"
services:
  db:
    image: "mariadb:10.6"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=overengineered-todo
      - MARIADB_USER=overengineered-todo
      - MARIADB_PASSWORD=password
    ports:
      - "3306:3306"