version: "3.9"
services:
  mariadb:
    image: "mariadb:10.6"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=ambicion
      - MARIADB_USER=ambicion-service
      - MARIADB_PASSWORD=password
  ambicion-service:
    image: bettercode.dev/ambicion-service:${CIRCLE_BRANCH}
    environment:
      - SPRING_PROFILES_ACTIVE=ct
      - OKTA_ISSUER=${OKTA_ISSUER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
    ports:
      - "9999:9999"
    depends_on:
      - mariadb
  tests:
    image: bettercode.dev/ambicion-service-tests:${CIRCLE_BRANCH}
    environment:
      - CT_CLIENT_ID=${CT_CLIENT_ID}
      - CT_CLIENT_SECRET=${CT_CLIENT_SECRET}
      - CT_OKTA_ISSUER=${CT_OKTA_ISSUER}
      - CT_TEST_USER=${CT_TEST_USER}
      - CT_TEST_PASSWORD=${CT_TEST_PASSWORD}
    depends_on:
      - ambicion-service
    command: dockerize -wait http://ambicion-service:9999/actuator/health -wait-retry-interval 2s -timeout 60s && ./gradlew componentTests
